configName: sam_e54_xpro_rnwf
folderName: sam_e54_xpro_rnwf_uart
format_version: v1.0
frameworkPath: C:\rnwf_H3
processor: ATSAME54P20A
projectName: sam_e54_xpro_rnwf_uart
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAME54_DFP\3.8.234
