
<#if SYS_RNWF_NET_SOCK_CONF == true>

<#if SYS_RNWF_NET_MODE0 == "SERVER">
#define SYS_RNWF_NET_BIND_TYPE0					SYS_RNWF_BIND_LOCAL
<#elseif SYS_RNWF_NET_MODE0 == "CLIENT">
#define SYS_RNWF_NET_BIND_TYPE0					SYS_RNWF_BIND_REMOTE 
</#if>

#define SYS_RNWF_NET_SOCK_PORT0					${SYS_RNWF_NET_SOCK_PORT0}

<#if SYS_RNWF_NET_SOCK_TYPE0 == "UDP">
#define SYS_RNWF_NET_SOCK_TYPE0					SYS_RNWF_SOCK_UDP
<#elseif SYS_RNWF_NET_SOCK_TYPE0 == "TCP">
#define SYS_RNWF_NET_SOCK_TYPE0					SYS_RNWF_SOCK_TCP 
</#if>

#define SYS_RNWF_NET_SOCK_ADDR0					"${SYS_RNWF_NET_SOCK_ADDR0}"

<#if SYS_RNWF_NET_ENABLE_TLS0 == true >
#define SYS_RNWF_TLS_ENABLE0					1
#define SYS_RNWF_NET_ROOT_CERT0					"${SYS_RNWF_NET_ROOT_CERT0}"

<#if SYS_RNWF_NET_DEVICE_KEY0 == "" >
#define SYS_RNWF_NET_DEVICE_KEY0				 NULL
<#else>
#define SYS_RNWF_NET_DEVICE_KEY0				"${SYS_RNWF_NET_DEVICE_KEY0}"
</#if>

<#if SYS_RNWD_NET_DEVICE_KEY_PWD0 == "" >
#define SYS_RNWD_NET_DEVICE_KEY_PWD0			 NULL
<#else>
#define SYS_RNWD_NET_DEVICE_KEY_PWD0			 "${SYS_RNWD_NET_DEVICE_KEY_PWD0}"
</#if>

<#if SYS_RNWF_NET_SERVER_NAME0 == "" >
#define SYS_RNWF_NET_SERVER_NAME0				NULL
<#else>
#define SYS_RNWF_NET_SERVER_NAME0				"${SYS_RNWF_NET_SERVER_NAME0}"
</#if>		

<#if SYS_RNWF_NET_DOMAIN_NAME0 == "" >
#define SYS_RNWF_NET_DOMAIN_NAME0				NULL
<#else>
#define SYS_RNWF_NET_DOMAIN_NAME0				"${SYS_RNWF_NET_DOMAIN_NAME0}"
</#if>

<#else>
#define SYS_RNWF_TLS_ENABLE0					0
</#if>

<#if SYS_RNWF_NET_NO_OF_SOCKS == 2>

<#if SYS_RNWF_NET_MODE1 == "SERVER">
#define SYS_RNWF_NET_BIND_TYPE1					SYS_RNWF_BIND_LOCAL
<#elseif SYS_RNWF_NET_MODE1 == "CLIENT">
#define SYS_RNWF_NET_BIND_TYPE1					SYS_RNWF_BIND_REMOTE 
<#elseif SYS_RNWF_NET_MODE1 == "MCAST">
#define SYS_RNWF_NET_BIND_TYPE1					SYS_RNWF_BIND_MCAST
<#elseif SYS_RNWF_NET_MODE1 == "NONE">
#define SYS_RNWF_NET_BIND_TYPE1					SYS_RNWF_BIND_NONE
</#if>

#define SYS_RNWF_NET_SOCK_PORT1					${SYS_RNWF_NET_SOCK_PORT1}

<#if SYS_RNWF_NET_SOCK_TYPE1 == "UDP">
#define SYS_RNWF_NET_SOCK_TYPE1					SYS_RNWF_SOCK_UDP
<#elseif SYS_RNWF_NET_SOCK_TYPE1 == "TCP">
#define SYS_RNWF_NET_SOCK_TYPE1					SYS_RNWF_SOCK_TCP 
</#if>


#define SYS_RNWF_NET_SOCK_ADDR1					"${SYS_RNWF_NET_SOCK_ADDR1}"

<#if SYS_RNWF_NET_ENABLE_TLS1 == true >
#define SYS_RNWF_TLS_ENABLE1					1
#define SYS_RNWF_NET_ROOT_CERT1					"${SYS_RNWF_NET_ROOT_CERT1}"

<#if SYS_RNWF_NET_DEVICE_KEY1 == "" >
#define SYS_RNWF_NET_DEVICE_KEY1				 NULL
<#else>
#define SYS_RNWF_NET_DEVICE_KEY1				"${SYS_RNWF_NET_DEVICE_KEY1}"
</#if>

<#if SYS_RNWD_NET_DEVICE_KEY_PWD1 == "" >
#define SYS_RNWD_NET_DEVICE_KEY_PWD1			 NULL
<#else>
#define SYS_RNWD_NET_DEVICE_KEY_PWD1			 "${SYS_RNWD_NET_DEVICE_KEY_PWD1}"
</#if>

<#if SYS_RNWF_NET_SERVER_NAME1 == "" >
#define SYS_RNWF_NET_SERVER_NAME1				NULL
<#else>
#define SYS_RNWF_NET_SERVER_NAME1				"${SYS_RNWF_NET_SERVER_NAME1}"
</#if>		

<#if SYS_RNWF_NET_DOMAIN_NAME1 == "" >
#define SYS_RNWF_NET_DOMAIN_NAME1				NULL
<#else>
#define SYS_RNWF_NET_DOMAIN_NAME1				"${SYS_RNWF_NET_DOMAIN_NAME1}"
</#if>

<#else>
#define SYS_RNWF_TLS_ENABLE1					0
</#if>
</#if>

</#if>
#define SYS_RNWF_NET_SockCallbackHandler  	    ${SYS_RNWF_NET_SOCKET_CALLBACK_HANDLER}