#define SYS_RNWF_MQTT_CLOUD_URL        		"${SYS_RNWF_MQTT_CLOUD_URL}"
#define SYS_RNWF_MQTT_CLOUD_PORT			${SYS_RNWF_MQTT_CLOUD_PORT}

<#if SYS_RNWF_MQTT_QOS_TYPE == "QOS0">
#define SYS_RNWF_MQTT_QOS_TYPE					SYS_RNWF_MQTT_QOS0
<#elseif SYS_RNWF_MQTT_QOS_TYPE == "QOS1">
#define SYS_RNWF_MQTT_QOS_TYPE					SYS_RNWF_MQTT_QOS1
<#elseif SYS_RNWF_MQTT_QOS_TYPE == "QOS2">
#define SYS_RNWF_MQTT_QOS_TYPE					SYS_RNWF_MQTT_QOS2
</#if>

<#if SYS_RNWF_MQTT_AZURE_RETAIN_FLAG == false>
#define SYS_RNWF_MQTT_RETAIN_TYPE				SYS_RNWF_NO_RETAIN
<#else>
#define SYS_RNWF_MQTT_RETAIN_TYPE				SYS_RNWF_RETAIN
</#if>
#define SYS_RNWF_MQTT_TOPIC_NAME        	    "${SYS_RNWF_MQTT_PUB_TOPIC_NAME}"

#define SYS_RNWF_MQTT_CLIENT_ID       			"${SYS_RNWF_MQTT_CLIENT_ID}"
#define SYS_RNWF_MQTT_SCOPE_ID       			"${SYS_RNWF_MQTT_SCOPE_ID}"
#define SYS_RNWF_MQTT_DEVICE_TEMPLATE			"${SYS_RNWF_MQTT_DEVICE_TEMPLATE}"
#define SYS_RNWF_MQTT_CLOUD_USER_NAME			"${SYS_RNWF_MQTT_CLOUD_USER_NAME}"
#define SYS_RNWF_MQTT_PASSWORD				"${SYS_RNWF_MQTT_PASSWORD}"
<#if SYS_RNWF_MQTT_AZURE_DPS_ENABLE == true > 
#define SYS_RNWF_MQTT_AZURE_DPS_ENABLE			1
<#elseif SYS_RNWF_MQTT_AZURE_DPS_ENABLE == false >
#define SYS_RNWF_MQTT_AZURE_DPS_ENABLE			0
</#if>

<#if SYS_RNWF_MQTT_CLOUD_URL?contains("aws")>
#define SYS_RNWF_AWS_FMT_TEMP_LIGHT      "{\\\"Temperature (C)\\\": %d,\\\"Light (lux)\\\":%d}"
#define SYS_RNWF_AWS_FMT_SHADOW_LIGHT    "{\\\"state\\\":{\\\"reported\\\":{\\\"toggle\\\": %d}}}"
#define SYS_RNWF_AWS_PUB_SHADOW_UPDATE   "$aws/things/"SYS_RNWF_MQTT_CLIENT_ID"/shadow/update"
</#if>

<#if SYS_MQTT_AZURE_ENABLE_TLS == true > 
#define SYS_RNWF_MQTT_SERVER_CERT            "${SYS_RNWF_MQTT_SERVER_CERT}"
#define SYS_RNWF_MQTT_DEVICE_CERT            "${SYS_RNWF_MQTT_DEVICE_CERT}"
#define SYS_RNWF_MQTT_DEVICE_KEY             "${SYS_RNWF_MQTT_DEVICE_KEY}"
#define SYS_RNWF_MQTT_DEVICE_KEY_PSK         "${SYS_RNWF_MQTT_DEVICE_KEY_PSK}"
#define SYS_RNWF_MQTT_TLS_SERVER_NAME        "${SYS_RNWF_MQTT_TLS_SERVER_NAME}"
#define SYS_RNWF_MQTT_TLS_DOMAIN_NAME        "${SYS_RNWF_MQTT_TLS_DOMAIN_NAME}"
</#if>

<#if  SYS_RNWF_MQTT_AZURE_SUBSCRIBE == true >
<#if  SYS_RNWF_MQTT_TOTAL_SUB_TOPICS == 1 > 
#define SYS_RNWF_MQTT_SUB_TOPIC_0            "${SYS_RNWF_MQTT_SUB_TOPIC0}"

<#elseif SYS_RNWF_MQTT_TOTAL_SUB_TOPICS == 2 >
#define SYS_RNWF_MQTT_SUB_TOPIC_0            "${SYS_RNWF_MQTT_SUB_TOPIC0}"
#define SYS_RNWF_MQTT_SUB_TOPIC_1            "${SYS_RNWF_MQTT_SUB_TOPIC1}"

<#elseif SYS_RNWF_MQTT_TOTAL_SUB_TOPICS == 3 >
#define SYS_RNWF_MQTT_SUB_TOPIC_0            "${SYS_RNWF_MQTT_SUB_TOPIC0}"
#define SYS_RNWF_MQTT_SUB_TOPIC_1            "${SYS_RNWF_MQTT_SUB_TOPIC1}"
#define SYS_RNWF_MQTT_SUB_TOPIC_2            "${SYS_RNWF_MQTT_SUB_TOPIC2}"

<#elseif SYS_RNWF_MQTT_TOTAL_SUB_TOPICS == 4 >
#define SYS_RNWF_MQTT_SUB_TOPIC_0            "${SYS_RNWF_MQTT_SUB_TOPIC0}"
#define SYS_RNWF_MQTT_SUB_TOPIC_1            "${SYS_RNWF_MQTT_SUB_TOPIC1}"
#define SYS_RNWF_MQTT_SUB_TOPIC_2            "${SYS_RNWF_MQTT_SUB_TOPIC2}"
#define SYS_RNWF_MQTT_SUB_TOPIC_3            "${SYS_RNWF_MQTT_SUB_TOPIC3}"

<#elseif SYS_RNWF_MQTT_TOTAL_SUB_TOPICS == 5 >
#define SYS_RNWF_MQTT_SUB_TOPIC_0            "${SYS_RNWF_MQTT_SUB_TOPIC0}"
#define SYS_RNWF_MQTT_SUB_TOPIC_1            "${SYS_RNWF_MQTT_SUB_TOPIC1}"
#define SYS_RNWF_MQTT_SUB_TOPIC_2            "${SYS_RNWF_MQTT_SUB_TOPIC2}"
#define SYS_RNWF_MQTT_SUB_TOPIC_3            "${SYS_RNWF_MQTT_SUB_TOPIC3}"
#define SYS_RNWF_MQTT_SUB_TOPIC_4            "${SYS_RNWF_MQTT_SUB_TOPIC4}"
</#if>
</#if>

#define SYS_RNWF_MQTT_CallbackHandler        ${SYS_RNWF_MQTT_CALLBACK_HANDLER}