
#define SYS_RNWF_TLS_USE_ECC608		1

<#if SYS_RNWF_ECC608_VARIANTS == "TNGTLS">
#define SYS_RNWF_TLS_ECC608_DEVTYPE					1 //TNGTLS
<#elseif SYS_RNWF_ECC608_VARIANTS == "TFLEX">
#define SYS_RNWF_TLS_ECC608_DEVTYPE					2 //TFLEX 
</#if>

